version: "3.3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    container_name: sun_sql_server  
    environment:
        SA_PASSWORD: "sun.1234567"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql # no space after :
volumes:
  sqlvolume:
    driver: local # a volume will be created automatically